### PR TITLE
Expose supported proxies

### PR DESCRIPTION
**Pull request by adfoster-r7**
Expose supported proxies for consumption in Metasploit framework

https://github.com/rapid7/metasploit-framework/pull/19683

### CODE REVIEW

**Review by smcintyre-r7 — COMMENTED** [review]
Related to my comment [here](https://github.com/rapid7/metasploit-framework/pull/19683/files#r1866083969), I think we want to differentiate between SOCKS4 and SOCKS4A. SOCKS4A is a superset of functionality that permits connecting by hostname, but an IPv4 address is required if it's SOCKS4.

**Comment by adfoster-r7** [comment]
Agreed :+1:

I've just created a new ticket to update rex-socket to support socks4a to unblock this effort https://github.com/rapid7/rex-socket/issues/70 :+1:

**Review by smcintyre-r7 — APPROVED** [review]
I have no changes to request, this looks good to me. I'll have it merged and released in a moment. Thanks!

**Review by AlphaOmega113 — COMMENTED** [review]
.github/workflows/ldap_acceptance.yml

**Pull request merged**
